---
- name: Install SSO systemd service files
  template:
    src: '{{ item.file }}.j2'
    dest: '{{ item.dest }}'
    mode: '0644'
  with_items:
  - file: 'fairdata-sso.service'
    dest: '/etc/systemd/system/{{ instance_name }}.service'
  - file: 'fairdata-sso.socket'
    dest: '/etc/systemd/system/{{ instance_name }}.socket'
  - file: 'fairdata-sso.env'
    dest: '{{ repo_dest }}/fairdata-sso.env'
  become: yes
  notify: Restart SSO systed service
  tags: sso-systemd

- name: Ensure SSO systemd service is started
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
  - '{{ instance_name }}.service'
  - '{{ instance_name }}.socket'
  become: yes
  tags: sso-systemd
