---
- name: Ensure Nginx is installed
  yum:
    name: 'nginx'
    state: 'latest'
  become: yes
  tags: sso-nginx

- name: Install SSO Nginx configuration
  template:
    src: 'fairdata-sso-nginx.conf.j2'
    dest: '/etc/nginx/conf.d/fairdata-sso-{{ repo_version }}.conf'
    mode: '0644'
  become: yes
  notify: Restart Nginx
  tags: sso-nginx
