---
- block:
  - name: Install SSO systemd service files
    template:
      src: '{{ item.file }}.j2'
      dest: '{{ item.dest }}'
      mode: '0644'
    with_items:
    - file: 'fairdata-sso.service'
      dest: '/etc/systemd/system/fairdata-{{ instance_name }}.service'
    - file: 'fairdata-sso.socket'
      dest: '/etc/systemd/system/fairdata-{{ instance_name }}.socket'
    - file: 'fairdata-sso.env'
      dest: '{{ repo_dest }}/fairdata-sso.env'
    become: yes
    notify: Restart SSO systed service
    tags: sso-systemd

  - name: Ensure SSO systemd service is started
    systemd:
      name: '{{ item }}'
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
    - 'fairdata-{{ instance_name }}.service'
    - 'fairdata-{{ instance_name }}.socket'
    become: yes
    tags: sso-systemd

  when: not delete_deployment

- block:
  - name: Ensure SSO systemd service is stopped and masked
    systemd:
      name: '{{ item }}'
      state: stopped
      masked: yes
    with_items:
    - 'fairdata-{{ instance_name }}.service'
    - 'fairdata-{{ instance_name }}.socket'
    become: yes
    ignore_errors: yes
    notify: Reload systed daemon
    tags: sso-systemd

  - name: Ensure SSO systemd service files are deleted
    file:
      path: '{{ item }}'
      state: 'absent'
    with_items:
    - '/etc/systemd/system/fairdata-{{ instance_name }}.service'
    - '/etc/systemd/system/fairdata-{{ instance_name }}.socket'
    become: yes
    notify: Reload systed daemon
    tags: sso-systemd

  when: delete_deployment
