---
- name: Ensure repository directory exists
  file:
    path: '{{ repo_dest }}'
    owner: '{{ deployer }}'
    state: 'directory'
    mode: '0755'
  become: yes
  tags: sso-repository

- name: Fetch SSO repository sources with git
  git:
    repo: '{{ repo_url }}'
    version: '{{ repo_version }}'
    key_file: '{{ repo_deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ repo_dest }}'
    force: yes
  when: repo_install_method == 'pull'
  tags: sso-repository

- name: Ensure repository contents are owned by the application user group
  file:
    path: '{{ repo_dest }}'
    group: '{{ application_group }}'
    recurse: yes
    state: directory
  become: yes
  tags: sso-repository
