---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes
  tags: sso-nginx

- name: Restart SSO systed service
  systemd:
    name: 'fairdata-sso'
    state: 'restarted'
  become: yes
  tags: sso-systemd

- name: Reload systed daemon
  systemd:
    daemon_reload: yes
  become: yes
  tags: sso-systemd
