---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes
  tags: sso-nginx

- name: Restart SSO systemd service
  systemd:
    name: 'fairdata-{{ instance_name }}'
    state: 'restarted'
  become: yes
  tags: sso-systemd

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
  tags: sso-systemd
